# -*- coding: utf-8 -*-
"""god is every where .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNCgO3ESSIDEKpVMqWiQP3iCaygXNaHL
"""
import streamlit as st
gemini_api = st.secrets["gemini_api"]

import google.generativeai as genai
genai.configure(api_key=userdata.get('gemini_api'))
model = genai.GenerativeModel("gemini-pro")

import requests
lat = 28.4595
lon = 77.0266
query = f"""[out:json];(node["amenity"="place_of_worship"]["religion"="hindu"](around:5000,{lat},{lon}););out body;"""
url = "https://overpass-api.de/api/interpreter"
headers = {
    'Content-Type': 'application/x-overpass-query',
    'User-Agent': 'ColabNotebook/1.0' # Adding a User-Agent header
}
response = requests.post(url, data=query, headers=headers)

# Improved error handling
if response.status_code == 200:
  try:
    data = response.json()
    print(data)
  except requests.exceptions.JSONDecodeError as e:
    print(f"JSONDecodeError: {e}")
    print(f"Response text: {response.text[:500]}...")
else:
  print(f"Request failed with status code: {response.status_code}")
  print(f"Response text: {response.text[:500]}...")

temples = []
for element in data['elements']:
    if 'tags' in element and 'name' in element['tags']:
        name = element['tags']['name']
        lat = element['lat']
        lon = element['lon']
        temples.append({'name': name, 'lat': lat, 'lon': lon})

print(f"Found {len(temples)} temples.")
for temple in temples:
    print(temple)

import requests
import wikipedia
from geopy.geocoders import Nominatim
from langchain_google_genai import ChatGoogleGenerativeAI

# Location
lat = 28.4595
lon = 77.0266

# Overpass API Query
query = f"""
[out:json];
(
  node["amenity"="place_of_worship"]["religion"="hindu"]
  (around:5000,{lat},{lon});
);
out body;
"""

url = "https://overpass-api.de/api/interpreter"

# Correcting to POST request with data and headers
headers = {
    'Content-Type': 'application/x-overpass-query',
    'User-Agent': 'ColabNotebook/1.0' # Adding a User-Agent header
}
response = requests.post(url, data=query, headers=headers)

# Improved error handling for the Overpass API response
if response.status_code == 200:
  try:
    data = response.json()
  except requests.exceptions.JSONDecodeError as e:
    print(f"JSONDecodeError: {e}")
    print(f"Response text: {response.text[:500]}...")
    data = {'elements': []} # Set empty data to avoid further errors
else:
  print(f"Request failed with status code: {response.status_code}")
  print(f"Response text: {response.text[:500]}...")
  data = {'elements': []} # Set empty data to avoid further errors


temples = []

for element in data['elements']:

    name = element['tags'].get('name', 'Unknown Temple')

    temple = {
        "name": name,
        "lat": element['lat'],
        "lon": element['lon']
    }

    temples.append(temple)

print(f"Found {len(temples)} temples.\n")

# Temple info
for temple in temples[:5]:

    print("="*50)
    print("Temple:", temple['name'])
    print("Latitude:", temple['lat'])
    print("Longitude:", temple['lon'])

    try:
        info = wikipedia.summary(temple['name'], sentences=3)
        print("\nDescription:")
        print(info)

    except:
        print("\nNo Wikipedia information found.")

    print("="*50)
    print("\n")

import requests

# Location (using the same as previous cells for consistency)
lat = 28.4595
lon = 77.0266

# Overpass API Query (copied from previous cell `sV7QZEOFKFnj`)
query = f"""
[out:json];
(
  node["amenity"="place_of_worship"]["religion"="hindu"]
  (around:5000,{lat},{lon});
);
out body;
"""

url = "https://overpass-api.de/api/interpreter"

headers = {
    'Content-Type': 'application/x-overpass-query',
    'User-Agent': 'ColabNotebook/1.0'
}
response = requests.post(url, data=query, headers=headers)

# Improved error handling for the Overpass API response
if response.status_code == 200:
  try:
    data = response.json()
  except requests.exceptions.JSONDecodeError as e:
    print(f"JSONDecodeError: {e}")
    print(f"Response text: {response.text[:500]}...")
    data = {'elements': []}
else:
  print(f"Request failed with status code: {response.status_code}")
  print(f"Response text: {response.text[:500]}...")
  data = {'elements': []}

temples = []

for element in data['elements']:
    name = element['tags'].get('name', 'Unknown Temple') # Safely get name, default to 'Unknown Temple'
    temple = {
        "name": name,
        "lat": element['lat'],
        "lon": element['lon']
    }
    temples.append(temple)


for temple in temples:
    maps_link = f"https://www.google.com/maps?q={temple['lat']},{temple['lon']}"
    print(maps_link)



from langchain_core.prompts import PromptTemplate
from langchain.chains import LLMChain
template = """You are a temple guide AI.
provide:
-histoy
-timings
-Cultural importance
Temple: {temple_name}"""
prompt = PromptTemplate(template=template, input_variables=["temple_name"])

import google.generativeai as genai
from google.colab import userdata

genai.configure(api_key=userdata.get('gemini_api'))
model = genai.GenerativeModel('gemini-flash-latest')

for temple in temples[:3]:
  final_prompt = prompt.format(temple_name=temple['name'])
  response = model.generate_content(final_prompt)
  print(response.text)

import google.generativeai as genai
from google.colab import userdata

genai.configure(api_key=userdata.get('gemini_api'))

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)
